version: "3.3"

services:
  cache:
    image: redis:latest
    ports:
      - 6378:6379
  db:
    build:
      context: .
      dockerfile: pg.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rootuser123
      - POSTGRES_DB=sire
    ports:
      - 5431:5432
  api:
    build: ./api
    volumes:
      - ${UPLOAD_PATH}:/sire-uploads
    ports:
      - 7000:8000
    depends_on:
      - db
      - cache
  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - api
